### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by soumith** [eladhoffer/lmdb.torch#1]
Your example usage seems to be not working...

th> db= lmdb.env()
missing argument: Path
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DB:open

Initializes a LMDB Database

> usage:
> DB:open{
>     Path = string                       -- Name of DataProvider
>     [MapSize = number]                  -- Size of map  [default = 1099511627776]
>     [NOSUBDIR = boolean]                --   [default = false]
>     [NOMETASYNC = boolean]              --   [default = false]
>     [RDONLY = boolean]                  --   [default = false]
>     [WRITEMAP = boolean]                --   [default = false]
>     [MAPASYNC = boolean]                --   [default = false]
>     [NOSYNC = boolean]                  --   [default = false]
>     [NOTLS = boolean]                   --   [default = false]
>     [NOLOCK = boolean]                  --   [default = false]
>     [Mode = number]                     --   [default = 664]
>     [MaxDBs = number]                   --   [default = 1]
>     [MaxReaders = number]               --   [default = 3]
>     [Name = string]                     --   [default = Data]
> }

DB:open{MapSize=number, Path=string}
DB:open(string, ...)

**Comment by eladhoffer** [comment]
Fixed example
