### ISSUE TITLE
MDB_val problem?

### ISSUE THREAD

**Issue by Junonia** [eladhoffer/lmdb.torch#4]
I am using lmdb to store the images, but I am having random MDB_NOTFOUND errors after some epochs.  The key is clearly in the database, otherwise it won't even finish one epoch.  I inspected the lmdb code,  I suspect lmdb.MDB_val function in init.lua is problematic.  The "value" is ffi.cast to a "void*" pointer, but the value object is local to the function and it will be garbage collected when out of scope according to http://luajit.org/ext_ffi_semantics.html (see section Garbage Collection of cdata Objects).  One possible solution would be return the value together with mdb_val and keep it for a while till transaction complete.  This probably also caused the problem when using integer keys.

**Comment by soumith** [comment]
Yea, makes sense to add a handle here: https://github.com/eladhoffer/lmdb.torch/blob/master/init.lua#L51

**Comment by eladhoffer** [comment]
You're right... I'll push a fix soon, will probably have to keep track on all pointers until a commit
