### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by live4today** [eladhoffer/lmdb.torch#7]
Hi,

I have a very weird problem.

I tried the example code on this webpage (https://github.com/eladhoffer/lmdb.torch) in TREPL. Everything seems fine.

However, when I copy the code into a lua file (say, test.lua), then I run the command `th test.lua`, it occurs a segmentation fault.

Could anyone help me on this issue? Thanks!

**Comment by live4today** [comment]
`txn:put()` is OK, but `txn:commit()` and `db:close()` will lead to segmentation fault.

**Comment by lim0606** [comment]
~~I have the same problem....~~

I had the same problem, and I twicked the function `commit()` for `txn`. It seems working for me. 

Best regards, 

Jaehyun
